name = "  zeeshan ali khan  "
print(name.upper())
print(name.lower())
print(name.title())
print(name.rstrip())
print(name.lstrip())
print(name.find("ali"))
print(name.replace("e", "a"))
print("zee" in name)
print("ahmad" not in name)
